services:
  postgres:
    image: postgres:16
    container_name: user_service_postgres
    environment:
      POSTGRES_DB: userDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_user:/var/lib/postgresql/data


volumes:
  postgres_data_user:
