spring:
   r2dbc:
    url: ${R2DBC_URL_USER:r2dbc:postgresql://localhost:5432/shop-flow-local}
    username: ${R2DBC_USERNAME:test}
    password: ${R2DBC_PASSWORD:test}

    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

jwt:
  secret: ${JWT_SECRET:this-is-my-super-secret-key-for-jwt-token-generation-123456}
  expiration:
    minutes: ${JWT_EXPIRATION_MINUTES:60}


logging:
  level:
    org.springframework.web: ${LOG_LEVEL_SPRING:INFO}
    com.example: ${LOG_LEVEL_APP:DEBUG}