name: user-service
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME : shopflow-user
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -B clean package

      - name: share jar with next runner
        uses: actions/upload-artifact@v4
        with:
          name: shopflow-user
          path: target/*.jar
  dockerimage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get jar from previous runner
        uses: actions/download-artifact@v4
        with:
          name: shopflow-user
          path: target/

      - name: setup docker build
        uses: docker/setup-buildx-action@v3

      - name: build and export image
        uses: docker/build-push-action@v6
        with:
          context: .
          outputs: type=docker,dest=/temp/shopflow-user.tar
          tags: ${{env.IMAGE_NAME}}
      - name: share tar file with next runner
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /temp/shopflow-user.tar



