name: user-service
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME : shopflow-user
  AWS_REGION: us-east-1
  ECR_REPOSITORY: user-service
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -B clean package

      - name: share jar with next runner
        uses: actions/upload-artifact@v4
        with:
          name: shopflow-user
          path: target/*.jar
  dockerimage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get jar from build
        uses: actions/download-artifact@v4
        with:
          name: shopflow-user
          path: target/

      - name: setup docker build
        uses: docker/setup-buildx-action@v3

      - name: build and export image
        uses: docker/build-push-action@v6
        with:
          context: .
          outputs: type=docker,dest=/tmp/shopflow-user.tar
          tags: ${{env.IMAGE_NAME}}
      - name: share tar file with next runner
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/shopflow-user.tar
  imagetoecr:
    needs: dockerimage
    runs-on: ubuntu-latest
    steps:
      - name: get image
        uses: actions/download-artifact@v4
        with:
          name: shopflow-user
          path: /tmp
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name : login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          docker tag ${{ env.IMAGE_NAME }}:latest $REGISTRY/${{ env.ECR_REPOSITORY }}:latest
          docker push $REGISTRY/${{ env.ECR_REPOSITORY }}:latest




